version: '2'

services:
  resume:
    image: superbuddy/ng-cli-nginx
    env_file: 
      - .env
    ports:
      - "${EXPOSED_DEV_PORT}:4200"
      - "${EXPOSED_DEBUGGER_PORT}:49152"
      - "${EXPOSED_PROD_PORT}:80"
    environment:
      - "VIRTUAL_HOST=${LETSENCRYPT_HOST}"
      - VIRTUAL_NETWORK=nginx-proxy
      - "VIRTUAL_PORT=${LETSENCRYPT_PORT}"
      - "LETSENCRYPT_HOST=${LETSENCRYPT_HOST}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_MAIL}"
    volumes:
      - /var/log/docker/jurien-cv:/var/log
      - "${PATH_TO_PROJECT}:/project"
    networks:
      - proxy-tier
      
networks:
  proxy-tier:
    external:
      name: nginx-proxy